service: cognito-auth

frameworkVersion: "2"

provider:
  name: aws
  lambdaHashingVersion: "20201221"
  stage: ${opt:stage, 'dev'}
  runtime: nodejs12.x
  region: us-east-1
  timeout: 3
  memorySize: 128
  endpointType: PRIVATE
  apiGateway:
    resourcePolicy:
      - Effect: Deny
        Principal: "*"
        Action: execute-api:Invoke
        Resource:
          - !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*
        Condition:
          StringNotEquals:
            aws:SourceVpce: ${file(serverless.${self:provider.stage}.yml):vpcEndpoint}
      - Effect: Allow
        Principal: "*"
        Action: execute-api:Invoke
        Resource:
          - !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: !Ref ApiGatewayAuthorizer
            scopes:
              - !Join ["/", [!Ref UserPoolResourceServer, "hello.get"]]

resources:
  - ${file(cfn-resources/apigateway-resources.yml)}
  - ${file(cfn-resources/cognito-resources.yml)}
