service: cognito-auth

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  timeout: 3
  memorySize: 128
  lambdaHashingVersion: "20201221"

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: !Ref ApiGatewayAuthorizer
            scopes:
              - !Join ["/", [!Ref UserPoolResourceServer, "hello.get"]]

resources:
  - ${file(cfn-resources/apigateway-resources.yml)}
  - ${file(cfn-resources/cognito-resources.yml)}
